<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Akiron.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\src\Modules\Crm\Akiron.Modules.Crm.csproj" />
    <ProjectReference Include="..\..\src\Modules\Reference\Akiron.Modules.Reference.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
